# Generated by Django 3.1.1 on 2020-09-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('folio', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Numero de folio')),
                ('empresa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Empresa cliente')),
                ('contacto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contacto empresa')),
            ],
        ),
    ]
