# Generated by Django 3.1.1 on 2020-09-05 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotizaciones', '0003_auto_20200905_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nombre cliente')),
                ('contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto empresa')),
                ('telefonoContacto', models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefono contacto')),
                ('correoContacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Correo contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.cliente')),
            ],
        ),
    ]
