# Generated by Django 3.1.1 on 2020-09-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0006_auto_20200905_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correoContacto',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo contacto'),
        ),
    ]
