# Generated by Django 3.1.1 on 2020-09-07 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100, null=True, verbose_name='Nombre cliente')),
                ('contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto empresa')),
                ('telefonoContacto', models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefono contacto')),
                ('correoContacto', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del producto')),
                ('marca', models.CharField(blank=True, max_length=255, null=True, verbose_name='Marca')),
                ('fabricante', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fabricante')),
                ('valorUnidad', models.IntegerField(blank=True, null=True, verbose_name='Valor por unidad')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, null=True, verbose_name='Nombre del servicio')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion del servicio')),
                ('valorMetroCuadrado', models.SmallIntegerField(blank=True, null=True, verbose_name='Valor por m2')),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrosCuadrados', models.SmallIntegerField(blank=True, null=True, verbose_name='Metros cuadrados')),
                ('cantidadProducto', models.SmallIntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.cliente', verbose_name='Cliente')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.producto')),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.servicio')),
            ],
        ),
    ]
