# Generated by Django 3.1.1 on 2020-09-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('empresa', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Numero de folio')),
                ('contacto', models.CharField(blank=True, max_length=10, null=True, verbose_name='Contacto empresa')),
                ('telefonoContacto', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefono contacto')),
                ('correoContacto', models.CharField(blank=True, max_length=10, null=True, verbose_name='Correo contacto')),
            ],
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='empresa',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='empresa',
            field=models.ManyToManyField(blank=True, to='cotizaciones.Cliente'),
        ),
    ]
