# Generated by Django 3.1.1 on 2020-09-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_cliente_cotizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del producto')),
                ('marca', models.CharField(blank=True, max_length=255, null=True, verbose_name='Marca')),
                ('fabricante', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fabricante')),
                ('valorUnidad', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, null=True, verbose_name='Nombre del servicio')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion del servicio')),
                ('valorMetroCuadrado', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='empresa',
            field=models.CharField(max_length=10, null=True, verbose_name='Nombre cliente'),
        ),
    ]
