# Generated by Django 3.1.1 on 2020-09-05 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0005_auto_20200905_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='valorUnidad',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Valor por unidad'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='valorMetroCuadrado',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Valor por m2'),
        ),
    ]
