# Generated by Django 3.1.1 on 2020-09-05 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0007_auto_20200905_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cantidadProducto',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='metrosCuadrados',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.producto'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.servicio'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='valorMetroCuadrado',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='valorProducto',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
