# Generated by Django 3.1.1 on 2020-09-07 16:13

from django.db import migrations


def create_data(apps, schema_editor):
    Cliente = apps.get_model('cotizaciones', 'Cliente')
    Cliente(empresa="Salfa S.A.",contacto="Cesar Cisternas",telefonoContacto="+56987654321",correoContacto="cesar@salfa.cl",).save()
    Cliente(empresa="Microsoft",contacto="Bill Gates",telefonoContacto="+56934567890",correoContacto="bill@microsoft.com",).save()
    Cliente(empresa="Amazon",contacto="Jeff Bezos",telefonoContacto="+56921098765",correoContacto="jeff@amazon.com",).save()
    Cliente(empresa="Tesla",contacto="Elon Musk",telefonoContacto="+56945678901",correoContacto="elon@tesla.com",).save()
    Cliente(empresa="Jumbo",contacto="Horst Paulmann",telefonoContacto="+56954321987",correoContacto="horst@jumbo.cl",).save()

    Producto = apps.get_model('cotizaciones', 'Producto')
    Producto(producto="Jotafloor Solvent Free Primer",marca="Jotun",fabricante="Codelpa",valorUnidad=289000,).save()
    Producto(producto="Jotafloor SL Universal",marca="Jotun",fabricante="Codelpa",valorUnidad=289000,).save()

    Servicio = apps.get_model('cotizaciones', 'Servicio')
    Servicio(nombre="Mantencion multicapa",descripcion="- Determinación del espesor de película seca\n- Determinación del espesor de película húmeda\n- Determinación tiempos de secado\n- Evaluación en ambiente corrosivo\n- Determinación de sólidos por volumenn* Incluye demarcacion y reparacion de juntas",valorMetroCuadrado=12000,).save()


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
