# Generated by Django 3.1.1 on 2020-12-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_cotizaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='servicio',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='servicios',
            field=models.ManyToManyField(blank=True, to='cotizaciones.Servicio'),
        ),
    ]
