# Generated by Django 3.1.1 on 2020-12-03 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_cotizaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='metrosCuadrados',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='servicio',
        ),
        migrations.CreateModel(
            name='ServiciosAgregados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.SmallIntegerField()),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.cotizacion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.servicio')),
            ],
        ),
    ]
