# Generated by Django 3.1.1 on 2020-12-06 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_cotizaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotiza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='metrosCuadrados',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='servicio',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='servicios',
            field=models.ManyToManyField(blank=True, to='cotizaciones.Servicio'),
        ),
        migrations.CreateModel(
            name='CotizaServicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad cotizada')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.cotiza')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='cotiza',
            name='servicios',
            field=models.ManyToManyField(through='cotizaciones.CotizaServicios', to='cotizaciones.Servicio'),
        ),
    ]
