# Generated by Django 3.1.1 on 2020-12-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_auto_20201203_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='servicios',
            field=models.ManyToManyField(through='cotizaciones.ServiciosAgregados', to='cotizaciones.Servicio'),
        ),
    ]
